# The Docker image that will be used to build your app
image: python:3.10-alpine
# Functions that should be executed before the build script is run
before_script:
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
